#!/bin/sh

package=""  # Default to empty package
target=""  # Default to empty target

# Parse options to the `pip` command
while getopts ":th:e"  opt; do
  case ${opt} in
    e )
      echo "typed e"
      ;;
    t )
      echo hai
      ;;
    h )
      echo "Usage:"
      echo "    pip -h                      Display this help message."
      echo "    pip install <package>       Install <package>."
      exit 0
      ;;
   \? )
     echo "Invalid Option: -$OPTARG" 1>&2
     exit 1
     ;;
  esac
done
shift $((OPTIND -1))
